# ----------------------------------------------------------
# Turbo C Makefile to build Cdata into an application
# ----------------------------------------------------------

# ----------------------------------------------------------
# Where Turbo C is installed
# ----------------------------------------------------------
TCPATH = C:\TOOLS\BC2AFW

CC = $(TCPATH)\BIN\bcc
LINK = $(TCPATH)\BIN\tlink

# ----------------------------------------------------------
# Application Name
# ----------------------------------------------------------
CDATA_APPL  = cbs
# ----------------------------------------------------------
# Memory Model
# ----------------------------------------------------------
MODEL = S

STARTUP = $(TCPATH)\lib\c0$(MODEL)
LIBS = cdata $(TCPATH)\lib\c$(MODEL)

# ----------------------------------------------------------
# An implicit rule to build .OBJ files from .C files
# ----------------------------------------------------------

.c.obj:
	$(CC) -P-c -c $<

# ----------------------------------------------------------
# An implicit rule to build .EXE files from .OBJ files
# ----------------------------------------------------------

.obj.exe:
	$(LINK) $(STARTUP) $* $(CDATA_APPL).obj, $*,,$(LIBS)

all :   cdata.lib   \
        schema.exe  \
        qd.exe      \
        ds.exe      \
        index.exe   \
        dbsize.exe  \
        dbinit.exe  \
        posttime.exe\
        payments.exe\
        invoice.exe \
        roster.exe

# ----------------------------------------------------------
# CDATA.LIB
# ----------------------------------------------------------

cdata.lib   :   ellist.obj  \
                cdata.obj   \
                screen.obj  \
                btree.obj   \
                datafile.obj\
                dblist.obj  \
                clist.obj   \
                filename.obj\
                sort.obj    \
                sys.obj
	del cdata.lib
	tlib cdata @cdata.bld

ellist.obj  :ellist.c cdata.h

cdata.obj   :cdata.c  cdata.h datafile.h btree.h keys.h

screen.obj  :screen.c cdata.h screen.h keys.h

btree.obj   :btree.c  cdata.h btree.h

datafile.obj: datafile.c    datafile.h

dblist.obj  :dblist.c cdata.h

clist.obj   :clist.c  cdata.h screen.h

sort.obj    :sort.c   cdata.h sort.h

sys.obj     :sys.c    cdata.h sys.h

filename.obj: filename.c cdata.h

# ----------------------------------------------------------
# The Base Schema
# ----------------------------------------------------------

schema.exe  :   schema.obj
	$(LINK) $(STARTUP) $*, $*,,$(LIBS)

schema.obj  :   schema.c

$(CDATA_APPL).c:    $(CDATA_APPL).sch schema.exe
	schema $(CDATA_APPL)

$(CDATA_APPL).obj   :   $(CDATA_APPL).c

# ----------------------------------------------------------
# Cdata Utility Programs
# ----------------------------------------------------------

qd.exe      :qd.obj     $(CDATA_APPL).obj   cdata.lib
ds.exe      :ds.obj     $(CDATA_APPL).obj   cdata.lib
index.exe   :index.obj  $(CDATA_APPL).obj   cdata.lib
dbsize.exe  :dbsize.obj $(CDATA_APPL).obj   cdata.lib
dbinit.exe  :dbinit.obj $(CDATA_APPL).obj   cdata.lib

qd.obj      :qd.c       cdata.h screen.h    keys.h
ds.obj      :ds.c       cdata.h
index.obj   :index.c    cdata.h
dbsize.obj  :dbsize.c   cdata.h btree.h     datafile.h
dbinit.obj  :dbinit.c   cdata.h datafile.h

# ----------------------------------------------------------
# Application-specific (CBS) programs
# ----------------------------------------------------------

posttime.exe:   posttime.obj    cbs.obj cdata.lib

payments.exe:   payments.obj    cbs.obj cdata.lib

invoice.exe:    invoice.obj     cbs.obj cdata.lib

roster.exe:     roster.obj      cbs.obj cdata.lib

posttime.obj:   posttime.c      cbs.h   screen.h    keys.h

payments.obj:   payments.c      cbs.h   screen.h    keys.h

invoice.obj:    invoice.c       cbs.h

roster.obj:     roster.c        cbs.h   sort.h

# ----------------------------------------------------------
# Databases/Indexes manipulation
# ----------------------------------------------------------

.dat.x01: 
	index $* 

clients.x01: clients.dat

projects.x01: projects.dat

consulta.x01: consulta.dat
	index $*nts

assignme.x01: assignme.dat
	index $*nts

ndxs:	clients.x01 projects.x01 consulta.x01 assignme.x01

initdb:	dbinit.exe
	dbinit
	ndxs

# ----------------------------------------------------------
# Clean-up
# ----------------------------------------------------------

cleandxs:
		del *.x??

cleandbs:	cleandxs
		del *.dat

cleanmaps:
	del *.map

cleanobjs:
	del *.obj

cleanexes:
	del *.exe

cleanall: \
	cleandbs  \
	cleanmaps \
	cleanobjs \
	cleanexes
